scenario: scenarios.nav_demo

agent:
  behavior_tree_xml: "default_bt.xml"
  namespaces: []

bt_runner:
  
  profiling_mode: false
  
  bt_tick_rate: 10
  bt_visualiser:
    enabled: true
    screen_width: 800
    screen_height: 600
    direction: "Vertical"